# Generated by Django 5.0 on 2024-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(unique=True)),
                ('data_emissao', models.DateField()),
                ('valor_total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtos', models.JSONField()),
                ('parcelas', models.JSONField()),
            ],
        ),
    ]
