# Generated by Django 5.0 on 2024-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_pedido',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
