# Generated by Django 5.0 on 2024-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_class', '0003_alter_venda_codigo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='adiantado',
            field=models.BooleanField(default=False),
        ),
    ]
