# Generated by Django 5.0 on 2024-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_class', '0004_venda_adiantado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_vencimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='numero_pedido_cliente',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
