# Generated by Django 5.0 on 2024-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_class', '0005_venda_data_vencimento_venda_numero_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='numero_pedido_cliente',
            field=models.CharField(default='', max_length=20),
        ),
    ]
